export const data  = {
  "iconLink": "agency_icons/minopex.png",
  "title": "minopex",
  "blogPosts": [
    {
      "jobTitle": "Engineering Supervisor – Electrical & Instrumentation",
      "publishedDate": "Published 13 November 2023",
      "expiryDate": "Closing Date: 20 November 2023",
      "location": "Polokwane Rural, Limpopo",
      "details": [
        "\n        <h1>Job Details</h1>\n    ",
        "\n        <div class=\"col-md-6\">\n            <div class=\"col-md-6\">\n\n\n\n\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"MinimumExperience\">Minimum experience</label>\n                    <span><label for=\"Associate\">Associate</label></span>\n                </div>\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"CompanyPrimaryIndustry\">Company primary industry</label>\n                    <span></span><label for=\"Mining_and_Metals\">Mining and Metals</label>\n                </div>\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"FunctionalAreaName\">Job functional area</label>\n                    <span><label for=\"Mining\">Mining</label></span>\n                </div>\n\n            </div>\n            <div class=\"col-md-6\">\n                                                            </div>\n        </div>\n\n\n    ",
        "\n        <div class=\"heading-blue\">\n            <h1>Job Description</h1>\n        </div>\n        <div class=\"vacancy-description\"><strong>Introduction</strong><br><br>This position will be based at the Bokoni Platinum Mine in Atok, Limpopo Province.<br><br><strong>Description<br><br></strong>The purpose of this position is to ensure that Electrical and Instrumentation maintenance and services are provided in line with organisational and client requirements.<br><br><strong><strong><strong>Duties &amp; Responsibilities:<br></strong></strong></strong><ul><li>Investigate, diagnose problems and breakdowns to determine resource requirements and order spares according to Company procedures.</li><li>Perform inspections in accordance with the Mine Health and Safety Act regulations and analyse breakdowns of the previous shift.</li><li>Over-inspect subordinates in their daily activities to ensure that maintenance is done according to organisational standards requirements.</li><li>Coordinate and monitor equipment availability to ensure adherence to production parameters.</li><li>Continuously analyse equipment efficiencies to recommend or implement improvements and changes to maximise operations.</li><li>Communicate equipment information and changes to relevant stakeholders to minimise production delays.</li><li>Ensure that all installations and equipment are safe and in good working order after task completion.</li><li>Attend to breakdowns immediately to minimize downtime.</li><li>Determine work schedules in conjunction with other engineering / process teams to ensure availability and optimal utilisation of equipment to the relevant sections and consult with production teams on maintenance activities that affects production.</li><li>Support the achievement of production and maintenance performance levels.</li><li>Perform administrative duties to ensure record accuracy and availability, budget compliance and spares availability</li></ul><br><strong>Qualification Requirements:<br></strong><ul><li>Grade 12 or equivalent qualification</li><li>Valid section 13 Trade Test / Section 26(D) certificate</li><li>Valid driver’s license code B, EB or C1</li><li>Own transport to attend to call outs</li><li>MV switching competency</li></ul><strong><br>Experience &amp; Skills Requirements:<br></strong><ul><li>Minimum 10 years’ experience in Electrical and Instrumentation maintenance with at least 3 - 4 years’ supervisory experience</li><li>English language proficiency</li><li>Time management skills</li><li>Employee Relations training</li><li>Supervisory training</li><li>Finance for non-financial managers training</li><li>Computer literate in MS Office</li><li>Relevant planned maintenance system training</li></ul></div>\n            <div class=\"vacancy-apply-btn margin-bob-30\">\n<a class=\"btn btn-primary\" href=\"https://minopex.simplify.hr/Vacancy/Apply/sdys7u\" rel=\"nofollow\">Apply</a>            </div>\n    "
      ],
      "apply": "https://minopex.simplify.hr/Vacancy/Apply/sdys7u",
      "iconLink": "agency_icons/minopex.png"
    },
    {
      "jobTitle": "Human Resources (HR) Administrator",
      "publishedDate": "Published 10 November 2023",
      "expiryDate": "Closing Date: 17 November 2023",
      "location": "Johannesburg, Gauteng",
      "details": [
        "\n        <h1>Job Details</h1>\n    ",
        "\n        <div class=\"col-md-6\">\n            <div class=\"col-md-6\">\n\n\n\n\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"MinimumExperience\">Minimum experience</label>\n                    <span><label for=\"Entry_Level\">Entry Level</label></span>\n                </div>\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"CompanyPrimaryIndustry\">Company primary industry</label>\n                    <span></span><label for=\"Mining_and_Metals\">Mining and Metals</label>\n                </div>\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"FunctionalAreaName\">Job functional area</label>\n                    <span><label for=\"Science\">Science</label></span>\n                </div>\n\n            </div>\n            <div class=\"col-md-6\">\n                                                            </div>\n        </div>\n\n\n    ",
        "\n        <div class=\"heading-blue\">\n            <h1>Job Description</h1>\n        </div>\n        <div class=\"vacancy-description\"><strong>Introduction</strong><br><br>This position will be based at the Head Office in Woodmead.<br><br><strong>Description<br></strong>This position is responsible to provide administrative support to the Human Resources Department to ensure that an effective and efficient service is provided to the business. The incumbent will be responsible for the documentation flow through in the group.<br>The incumbent will also be responsible for the maintenance of a shared drive human resources platform, ensuring that the database information is always up to date<br><br><strong>Duties &amp; Responsibilities:<br></strong><ul><li>Provide administrative support services in order to ensure efficiency and effectiveness within the HR Department</li><li>Ensure compliance with HR Policies and Procedures, Collective Labour Agreements and with relevant legislation</li><li>Implement effective administration systems</li><li>Analyse reports and data for accuracy</li><li>Maintain electronic personnel filing system; ensure all records are kept and up to date</li><li>Scheduling, administration and record keeping of performance appraisals, drafting of documents and KPI's</li><li>Manage exit process</li><li>Accurate compilation of weekly and month end HR reports</li><li>Compile agendas and minutes</li><li>Report on the HR related information for BBBEE purpose</li><li>Updating of job descriptions</li><li>Assisting with all administration related to SLP’s, Employment Equity etc.</li><li>Maintaining an adequate inventory of office supplies for the HR department</li><li>Assist in the planning and preparation of meetings, conference calls etc.</li><li>Coordination of travel and accommodation bookings for the HR department</li></ul><strong>Qualification Requirements:</strong><br><ul><li>Grade 12</li><li>Secretarial, Administration, Payroll or Human Resources Diploma will be advantageous.</li></ul><strong>Experience &amp; Skills Requirements:</strong><br><ul><li>At least 5 years’ experience in a HR administration role is required</li><li>Knowledge of Employment Legislation, LRA,EEA,BCEA SDA etc</li><li>Experience in the mining, mineral processing or related industries is preferred</li><li>Strong organisational and time management skills</li><li>Excellent administrative skills</li><li>Excellent communication and interpersonal skills</li><li>Ability to work under pressure with a sense of urgency to meet deadlines</li><li>Advanced Proficient in Microsoft Office Suite – Outlook, Word, Excel, Powerpoint</li><li>Proficient in HRMIS, IRS,ERP</li></ul><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br></div>\n            <div class=\"vacancy-apply-btn margin-bob-30\">\n<a class=\"btn btn-primary\" href=\"https://minopex.simplify.hr/Vacancy/Apply/5wg5rh\" rel=\"nofollow\">Apply</a>            </div>\n    "
      ],
      "apply": "https://minopex.simplify.hr/Vacancy/Apply/5wg5rh",
      "iconLink": "agency_icons/minopex.png"
    },
    {
      "jobTitle": "Process Operator – Plant",
      "publishedDate": "Published 10 November 2023",
      "expiryDate": "Closing Date: 17 November 2023",
      "location": "Saldanha Bay Rural, Western Cape",
      "details": [
        "\n        <h1>Job Details</h1>\n    ",
        "\n        <div class=\"col-md-6\">\n            <div class=\"col-md-6\">\n\n\n\n\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"MinimumExperience\">Minimum experience</label>\n                    <span><label for=\"Associate\">Associate</label></span>\n                </div>\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"CompanyPrimaryIndustry\">Company primary industry</label>\n                    <span></span><label for=\"Mining_and_Metals\">Mining and Metals</label>\n                </div>\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"FunctionalAreaName\">Job functional area</label>\n                    <span><label for=\"Mining\">Mining</label></span>\n                </div>\n\n            </div>\n            <div class=\"col-md-6\">\n                                                            </div>\n        </div>\n\n\n    ",
        "\n        <div class=\"heading-blue\">\n            <h1>Job Description</h1>\n        </div>\n        <div class=\"vacancy-description\"><strong>Introduction</strong> <br><br>This position will be based in the Saldanha Bay Municipality area in the Western Cape.<br><br><strong>Description</strong> <br><br>The purpose of this position is to operate equipment correctly and responsibly in accordance to the procedural requirements, ensuring respective plant sections function effectively and within production parameters whilst adhering to Health and Safety standards.<br><br><strong>Duties and Responsibilities</strong> <br><ul><li>Continuously monitor plant equipment and report to the Control Room / Section Supervisor</li><li>Ensure adherence to the specified process parameters within the respective sections</li><li>Maintain a high standard of housekeeping</li><li>Support the achievement of production performance levels</li><li>Perform basic maintenance activities to assist maintenance staff and replace screens, idlers etc. where engineering is not required</li><li>Conduct plant operational tasks within specified sections.</li><li>Ensure samples handling and preparation are done according to standard</li><li>Conduct manual process stream spot checks</li></ul><strong>Qualification Requirements</strong> <br><ul><li>Grade 12</li><li>National Certificate Mineral Processing Level 2 or equivalent Mineral Processing qualification will be advantageous</li></ul><strong>Experience and Skills&nbsp;Requirements</strong> <br><ul><li>Minimum 1 to 2 years’ experience as a Process Attendant in a factory / mining production environment</li><li>Experience within the mineral processing industry will be advantageous</li><li>English language proficiency</li><li>Time management skills</li><li>Computer literacy and MS Office competency will be advantageous</li><li>Grade 12 maths and science will be advantageous</li></ul></div>\n            <div class=\"vacancy-apply-btn margin-bob-30\">\n<a class=\"btn btn-primary\" href=\"https://westcoastplantoperationsptyltd.simplify.hr/Vacancy/Apply/8fxa6m\" rel=\"nofollow\">Apply</a>            </div>\n    "
      ],
      "apply": "https://westcoastplantoperationsptyltd.simplify.hr/Vacancy/Apply/8fxa6m",
      "iconLink": "agency_icons/minopex.png"
    }
  ]
}
