export const data  = {
  "iconLink": "agency_icons/minopex.png",
  "title": "minopex",
  "blogPosts": [
    {
      "jobTitle": "Human Resources (HR) Administrator",
      "publishedDate": "Published 10 November 2023",
      "expiryDate": "Closing Date: 17 November 2023",
      "location": "Johannesburg, Gauteng",
      "details": [
        " <h1>Job Details</h1>\n    ",
        " <div class=\"col-md-6\">     <div class=\"col-md-6\">\n\n\n\n         <div class=\"row padding-bottom-10\">             <label class=\"job-detail-bold-header\" for=\"MinimumExperience\">Minimum experience</label>             <span><label for=\"Entry_Level\">Entry Level</label></span>         </div>         <div class=\"row padding-bottom-10\">             <label class=\"job-detail-bold-header\" for=\"CompanyPrimaryIndustry\">Company primary industry</label>             <span></span><label for=\"Mining_and_Metals\">Mining and Metals</label>         </div>         <div class=\"row padding-bottom-10\">             <label class=\"job-detail-bold-header\" for=\"FunctionalAreaName\">Job functional area</label>             <span><label for=\"Science\">Science</label></span>         </div>\n     </div>     <div class=\"col-md-6\">                                                     </div> </div>\n\n\n    ",
        " <div class=\"heading-blue\">     <h1>Job Description</h1> </div> <div class=\"vacancy-description\"><strong>Introduction</strong><br><br>This position will be based at the Head Office in Woodmead.<br><br><strong>Description<br></strong>This position is responsible to provide administrative support to the Human Resources Department to ensure that an effective and efficient service is provided to the business. The incumbent will be responsible for the documentation flow through in the group.<br>The incumbent will also be responsible for the maintenance of a shared drive human resources platform, ensuring that the database information is always up to date<br><br><strong>Duties &amp; Responsibilities:<br></strong><ul><li>Provide administrative support services in order to ensure efficiency and effectiveness within the HR Department</li><li>Ensure compliance with HR Policies and Procedures, Collective Labour Agreements and with relevant legislation</li><li>Implement effective administration systems</li><li>Analyse reports and data for accuracy</li><li>Maintain electronic personnel filing system; ensure all records are kept and up to date</li><li>Scheduling, administration and record keeping of performance appraisals, drafting of documents and KPI's</li><li>Manage exit process</li><li>Accurate compilation of weekly and month end HR reports</li><li>Compile agendas and minutes</li><li>Report on the HR related information for BBBEE purpose</li><li>Updating of job descriptions</li><li>Assisting with all administration related to SLP’s, Employment Equity etc.</li><li>Maintaining an adequate inventory of office supplies for the HR department</li><li>Assist in the planning and preparation of meetings, conference calls etc.</li><li>Coordination of travel and accommodation bookings for the HR department</li></ul><strong>Qualification Requirements:</strong><br><ul><li>Grade 12</li><li>Secretarial, Administration, Payroll or Human Resources Diploma will be advantageous.</li></ul><strong>Experience &amp; Skills Requirements:</strong><br><ul><li>At least 5 years’ experience in a HR administration role is required</li><li>Knowledge of Employment Legislation, LRA,EEA,BCEA SDA etc</li><li>Experience in the mining, mineral processing or related industries is preferred</li><li>Strong organisational and time management skills</li><li>Excellent administrative skills</li><li>Excellent communication and interpersonal skills</li><li>Ability to work under pressure with a sense of urgency to meet deadlines</li><li>Advanced Proficient in Microsoft Office Suite – Outlook, Word, Excel, Powerpoint</li><li>Proficient in HRMIS, IRS,ERP</li></ul><br</div>     <div class=\"vacancy-apply-btn margin-bob-30\">\n<a class=\"btn btn-primary\" href=\"https://minopex.simplify.hr/Vacancy/Apply/5wg5rh\" rel=\"nofollow\">Apply</a>            </div>\n    "
      ],
      "apply": "https://minopex.simplify.hr/Vacancy/Apply/5wg5rh",
      "iconLink": "agency_icons/minopex.png"
    },
    {
      "jobTitle": "Process Operator – Plant",
      "publishedDate": "Published 10 November 2023",
      "expiryDate": "Closing Date: 17 November 2023",
      "location": "Saldanha Bay Rural, Western Cape",
      "details": [
        " <h1>Job Details</h1>\n    ",
        " <div class=\"col-md-6\">     <div class=\"col-md-6\">\n\n\n\n         <div class=\"row padding-bottom-10\">             <label class=\"job-detail-bold-header\" for=\"MinimumExperience\">Minimum experience</label>             <span><label for=\"Associate\">Associate</label></span>         </div>         <div class=\"row padding-bottom-10\">             <label class=\"job-detail-bold-header\" for=\"CompanyPrimaryIndustry\">Company primary industry</label>             <span></span><label for=\"Mining_and_Metals\">Mining and Metals</label>         </div>         <div class=\"row padding-bottom-10\">             <label class=\"job-detail-bold-header\" for=\"FunctionalAreaName\">Job functional area</label>             <span><label for=\"Mining\">Mining</label></span>         </div>\n     </div>     <div class=\"col-md-6\">                                                     </div> </div>\n\n\n    ",
        " <div class=\"heading-blue\">     <h1>Job Description</h1> </div> <div class=\"vacancy-description\"><strong>Introduction</strong> <br><br>This position will be based in the Saldanha Bay Municipality area in the Western Cape.<br><br><strong>Description</strong> <br><br>The purpose of this position is to operate equipment correctly and responsibly in accordance to the procedural requirements, ensuring respective plant sections function effectively and within production parameters whilst adhering to Health and Safety standards.<br><br><strong>Duties and Responsibilities</strong> <br><ul><li>Continuously monitor plant equipment and report to the Control Room / Section Supervisor</li><li>Ensure adherence to the specified process parameters within the respective sections</li><li>Maintain a high standard of housekeeping</li><li>Support the achievement of production performance levels</li><li>Perform basic maintenance activities to assist maintenance staff and replace screens, idlers etc. where engineering is not required</li><li>Conduct plant operational tasks within specified sections.</li><li>Ensure samples handling and preparation are done according to standard</li><li>Conduct manual process stream spot checks</li></ul><strong>Qualification Requirements</strong> <br><ul><li>Grade 12</li><li>National Certificate Mineral Processing Level 2 or equivalent Mineral Processing qualification will be advantageous</li></ul><strong>Experience and Skills&nbsp;Requirements</strong> <br><ul><li>Minimum 1 to 2 years’ experience as a Process Attendant in a factory / mining production environment</li><li>Experience within the mineral processing industry will be advantageous</li><li>English language proficiency</li><li>Time management skills</li><li>Computer literacy and MS Office competency will be advantageous</li><li>Grade 12 maths and science will be advantageous</li></ul></div>     <div class=\"vacancy-apply-btn margin-bob-30\">\n<a class=\"btn btn-primary\" href=\"https://westcoastplantoperationsptyltd.simplify.hr/Vacancy/Apply/8fxa6m\" rel=\"nofollow\">Apply</a>            </div>\n    "
      ],
      "apply": "https://westcoastplantoperationsptyltd.simplify.hr/Vacancy/Apply/8fxa6m",
      "iconLink": "agency_icons/minopex.png"
    }
  ]
}
